name: Transformar Valors Radar NC

on:
  workflow_dispatch: # Permet l'execució manual

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codi
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instal·lar dependències
        run: |
          python -m pip install --upgrade pip
          pip install xarray netcdf4 numpy

      - name: Executar transformació
        run: python transform_nc.py

      - name: Pujar canvis
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add dades_radar/*.nc
          git commit -m "Transformació de valors radar aplicada" || echo "Sense canvis per commitejar"
          git push
